fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

register_participant:
    path:     /register/for/event/{id}
    defaults: { _controller: EventBundle:Event:registerUserForEvent }
    requirements:
            id:  \d+

unregister_participant:
    path:   /unregister/for/event/{id}
    defaults: { _controller: EventBundle:Event:unregisterUserForEvent }
    requirements:
            id:  \d+

all_user_events:
    path:     /all/my/events
    defaults: { _controller: EventBundle:Event:allUserEvent }
    requirements:
            id:  \d+

add_photo_link:
    path:     /add/photo
    defaults: { _controller: EventBundle:Event:addPhoto }