fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

register_new_participant:
    path:     /register/for/event/{id}
    defaults: { _controller: EventBundle:Event:registerUserForEvent }
    requirements:
            id:  \d+

all_user_events:
    path:     /all/my/events
    defaults: { _controller: EventBundle:Event:allUserEvent }
    requirements:
            id:  \d+


