create_event:
    path:     /create/event
    defaults: { _controller: EventBundle:Event:createEvent }

edit_event:
    pattern:  /edit/event/{id}
    defaults: { _controller: EventBundle:Event:editEvent }
    requirements:
        id:  \d+

all_events:
    path:     /all/events
    defaults: { _controller: EventBundle:Event:allEvents }

create_new_activity:
    path:     /create/activity
    defaults: { _controller: EventBundle:Activity:createActivity }